
import React, { useState } from 'react';
import { MarketingPlan } from '../types';

const ContentDisplay: React.FC<{ plan: MarketingPlan }> = ({ plan }) => {
  const [copied, setCopied] = useState(false);

  const safeCaption = plan?.postCaption || "Caption generating...";
  const safeHashtags = Array.isArray(plan?.hashtags) ? plan.hashtags : [];
  const safeProductName = plan?.productName || "Product";
  const safeStrategy = plan?.strategyAdvice || "Analyzing strategy...";
  const safeTime = plan?.postingTimeSuggestion || "Anytime";
  const safeScript = plan?.videoScript || "Generating script...";
  const safeSources = Array.isArray(plan?.sources) ? plan.sources : [];

  const fullPost = `${safeCaption}\n\n${safeHashtags.join(' ')}`;

  const copy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const openFacebook = () => {
    window.open('https://www.facebook.com', '_blank');
  };

  const downloadPlan = () => {
    const content = `
Product: ${safeProductName}
-----------------------------------
FACEBOOK POST CAPTION:
${safeCaption}

HASHTAGS:
${safeHashtags.join(' ')}

SALES STRATEGY:
${safeStrategy}

POSTING TIME:
${safeTime}

VIDEO SCRIPT (TikTok/Reels):
${safeScript}
-----------------------------------
Generated by ဈေးသည် AI Agent
    `;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${safeProductName.replace(/\s+/g, '_')}_Marketing_Plan.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-12 duration-1000 ease-out">
      {/* Header Section */}
      <div className="mb-8 px-2 flex flex-col md:flex-row justify-between items-start md:items-end gap-6 transition-all">
        <div className="animate-in slide-in-from-left-8 duration-700 delay-100">
          <h2 className="text-3xl md:text-5xl font-black text-slate-900 tracking-tight mb-3 flex items-center gap-3">
            <span className="text-indigo-600 animate-pulse">✦</span> {safeProductName}
          </h2>
          <div className="flex items-center gap-3">
            <span className="relative flex h-3 w-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3 w-3 bg-indigo-500"></span>
            </span>
            <p className="text-indigo-600 font-black text-[10px] md:text-xs tracking-[0.3em] uppercase">
              AI Market Intelligence Engaged
            </p>
          </div>
        </div>
        
        <button 
          onClick={downloadPlan}
          className="group w-full md:w-auto px-8 py-4 bg-white border-2 border-slate-900 text-slate-900 font-black rounded-2xl text-[10px] uppercase tracking-widest hover:bg-slate-900 hover:text-white transition-all duration-300 shadow-xl hover:shadow-2xl hover:-translate-y-1 active:scale-95 flex items-center justify-center gap-3 overflow-hidden"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 transform transition-transform group-hover:bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download Market Report
        </button>
      </div>

      {/* Main Facebook Card */}
      <div className="animate-in fade-in zoom-in-95 duration-700 delay-200 bg-white rounded-[3rem] shadow-2xl border-t-[14px] border-slate-900 overflow-hidden relative ring-1 ring-slate-100 group">
        <div className="bg-slate-900 p-8 flex flex-wrap justify-between items-center gap-6">
          <div className="flex items-center gap-4">
            <div className="bg-indigo-500 w-3 h-3 rounded-full animate-pulse shadow-[0_0_12px_rgba(99,102,241,0.8)]"></div>
            <h3 className="text-white font-black text-[11px] tracking-[0.25em] uppercase">
              Omnichannel Viral Post
            </h3>
          </div>
          <div className="flex gap-3 w-full md:w-auto">
            <button 
              onClick={() => copy(fullPost)} 
              className={`flex-1 md:flex-none text-[10px] font-black ${copied ? 'bg-green-600 border-green-800' : 'bg-gradient-to-r from-indigo-600 to-violet-600 border-indigo-900 hover:brightness-110'} text-white px-7 py-4 rounded-2xl transition-all duration-300 shadow-xl hover:shadow-indigo-500/25 active:scale-95 border-b-4 flex items-center justify-center gap-2`}
            >
              {copied ? '✓ COPIED' : '📋 COPY CONTENT'}
            </button>
            <button 
              onClick={openFacebook}
              className="flex-1 md:flex-none text-[10px] font-black bg-[#1877F2] text-white px-7 py-4 rounded-2xl transition-all duration-300 shadow-xl hover:shadow-blue-500/25 hover:brightness-110 active:scale-95 border-b-4 border-[#0e5cad] flex items-center justify-center gap-2"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>
              FACEBOOK
            </button>
          </div>
        </div>
        
        <div className="p-8 md:p-12 bg-gradient-to-br from-white via-white to-indigo-50/20">
          <div className="relative group/caption bg-slate-50 border-l-[10px] border-indigo-600 p-8 md:p-10 rounded-3xl mb-12 shadow-inner transition-transform hover:translate-x-1 duration-300">
            <div className="absolute top-4 right-6 opacity-5 select-none">
              <svg width="40" height="40" fill="currentColor" viewBox="0 0 24 24"><path d="M14.017 21L14.017 18C14.017 16.8954 14.9124 16 16.017 16H19.017C19.5693 16 20.017 15.5523 20.017 15V9C20.017 8.44772 19.5693 8 19.017 8H15.017C14.4647 8 14.017 8.44772 14.017 9V12C14.017 12.5523 13.5693 13 13.017 13H11.017C10.4647 13 10.017 12.5523 10.017 12V9C10.017 7.34315 11.3602 6 13.017 6H19.017C20.6739 6 22.017 7.34315 22.017 9V15C22.017 17.7614 19.7784 20 17.017 20H15.017C14.4647 20 14.017 19.5523 14.017 19V21H14.017ZM3.01705 21L3.01705 18C3.01705 16.8954 3.91248 16 5.01705 16H8.01705C8.56933 16 9.01705 15.5523 9.01705 15V9C9.01705 8.44772 8.56933 8 8.01705 8H4.01705C3.46476 8 3.01705 8.44772 3.01705 9V12C3.01705 12.5523 2.56933 13 2.01705 13H0.0170471C-0.535238 13 -0.982953 12.5523 -0.982953 12V9C-0.982953 7.34315 0.360195 6 2.01705 6H8.01705C9.6739 6 11.017 7.34315 11.017 9V15C11.017 17.7614 8.77847 20 6.01705 20H4.01705C3.46476 20 3.01705 19.5523 3.01705 19V21H3.01705Z"/></svg>
            </div>
            <p className="whitespace-pre-line text-slate-800 font-bold leading-relaxed text-xl md:text-2xl pr-4">
              {safeCaption}
            </p>
          </div>
          
          <div className="flex flex-wrap gap-3 mb-12">
            {safeHashtags.map((h, i) => (
              <span 
                key={i} 
                className="text-[10px] md:text-[11px] font-black text-white bg-slate-900 px-5 py-3 rounded-2xl shadow-lg hover:bg-indigo-600 transition-all hover:-translate-y-1 cursor-default"
                style={{ animationDelay: `${i * 100}ms` }}
              >
                {h}
              </span>
            ))}
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
             <div className="group/card bg-gradient-to-br from-indigo-600 to-indigo-900 p-10 rounded-[3rem] text-white shadow-2xl relative overflow-hidden transition-all duration-500 hover:shadow-indigo-300">
                <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full -mr-16 -mt-16 blur-2xl group-hover/card:bg-white/10 transition-colors"></div>
                <span className="text-[10px] font-black text-indigo-200 uppercase tracking-[0.4em] block mb-5">Psychological Trigger</span>
                <p className="text-lg md:text-xl font-black leading-tight italic tracking-tight">{safeStrategy}</p>
             </div>
             <div className="group/card bg-slate-900 p-10 rounded-[3rem] text-white shadow-2xl relative overflow-hidden transition-all duration-500 hover:shadow-slate-400">
                <div className="absolute bottom-0 left-0 w-32 h-32 bg-indigo-500/5 rounded-full -ml-16 -mb-16 blur-2xl group-hover/card:bg-indigo-500/10 transition-colors"></div>
                <span className="text-[10px] font-black text-slate-400 uppercase tracking-[0.4em] block mb-5">Post Timing</span>
                <p className="text-lg md:text-xl font-black leading-tight italic tracking-tight">{safeTime}</p>
             </div>
          </div>

          {safeSources.length > 0 && (
            <div className="mt-14 pt-10 border-t-2 border-slate-100 animate-in fade-in duration-1000 delay-500">
              <h4 className="text-[11px] font-black text-slate-400 uppercase tracking-[0.3em] mb-6 flex items-center gap-4">
                <span className="h-px bg-slate-200 flex-1"></span>
                Market Grounding
                <span className="h-px bg-slate-200 flex-1"></span>
              </h4>
              <div className="flex flex-col gap-4">
                {safeSources.map((url, idx) => (
                  <a 
                    key={idx}
                    href={url} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="group/link text-[10px] text-slate-500 hover:text-indigo-600 truncate font-black bg-white p-5 rounded-3xl border-2 border-slate-50 shadow-sm transition-all hover:shadow-lg hover:border-indigo-100 flex items-center gap-4"
                  >
                    <span className="w-8 h-8 rounded-full bg-slate-50 text-slate-400 flex items-center justify-center font-bold text-xs group-hover/link:bg-indigo-50 group-hover/link:text-indigo-600 transition-colors">
                      {idx + 1}
                    </span>
                    <span className="flex-1 truncate group-hover/link:underline">{url}</span>
                    <svg className="w-4 h-4 opacity-0 group-hover/link:opacity-100 transition-opacity" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/></svg>
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Video Script Card */}
      <div className="animate-in fade-in slide-in-from-bottom-12 duration-1000 delay-300 bg-white rounded-[3rem] p-10 md:p-14 border border-slate-200 shadow-2xl overflow-hidden relative group/script">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-10 gap-6">
          <h4 className="font-black text-slate-900 flex items-center gap-5 text-2xl md:text-3xl">
            <div className="bg-gradient-to-tr from-indigo-600 to-violet-600 p-4 rounded-2xl text-white shadow-xl rotate-3 group-hover/script:rotate-0 transition-transform duration-500">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" viewBox="0 0 20 20" fill="currentColor">
                <path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z" />
              </svg>
            </div>
            TikTok & Reels Screenplay
          </h4>
          <button 
            onClick={() => copy(safeScript)}
            className="group/btn w-full md:w-auto px-6 py-4 bg-slate-50 hover:bg-indigo-600 hover:text-white rounded-2xl transition-all duration-300 text-slate-600 font-black text-xs uppercase tracking-widest flex items-center justify-center gap-3 border-2 border-transparent hover:border-indigo-400"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
            </svg>
            COPY SCRIPT
          </button>
        </div>
        
        <div className="relative">
          <div className="bg-slate-900 p-10 md:p-14 rounded-[2.5rem] border-2 border-slate-800 shadow-2xl relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/5 rounded-full -mr-32 -mt-32 blur-3xl"></div>
            <p className="whitespace-pre-line text-indigo-100/90 text-sm md:text-base font-mono leading-relaxed font-bold relative z-10 selection:bg-indigo-500 selection:text-white">
              {safeScript}
            </p>
          </div>
          <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 bg-white px-8 py-2 rounded-full border border-slate-200 shadow-lg">
             <p className="text-[10px] text-slate-400 font-black uppercase tracking-[0.4em] text-center">AI Logic Optimized</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContentDisplay;
